language: en

features:
  rainfeature: true
  utilfeature: true
  sludgefeature: false
  worldgenfeature: false

auto-restart:
  enabled: true
  cron: "0 0 5 * * *" # Every day at 5 AM server time will trigger the server restart countdown (10 minutes).